package com.dicampus.j2ee.model;
// Generated 24 ago 2026, 14:07:38 by Hibernate Tools 5.4.33.Final



/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private static final long serialVersionUID = -3872184608711365174L;
	 private Long asiId;
     private long asiCursoId;
     private String asiNombre;
     private Integer asiHorasSemanales;
     private Boolean asiOptativa;

    public Asignatura() {
    }

	
    public Asignatura(long asiCursoId) {
        this.asiCursoId = asiCursoId;
    }
    public Asignatura(long asiCursoId, String asiNombre, Integer asiHorasSemanales, Boolean asiOptativa) {
       this.asiCursoId = asiCursoId;
       this.asiNombre = asiNombre;
       this.asiHorasSemanales = asiHorasSemanales;
       this.asiOptativa = asiOptativa;
    }
   
    public Long getAsiId() {
        return this.asiId;
    }
    
    public void setAsiId(Long asiId) {
        this.asiId = asiId;
    }
    public long getAsiCursoId() {
        return this.asiCursoId;
    }
    
    public void setAsiCursoId(long asiCursoId) {
        this.asiCursoId = asiCursoId;
    }
    public String getAsiNombre() {
        return this.asiNombre;
    }
    
    public void setAsiNombre(String asiNombre) {
        this.asiNombre = asiNombre;
    }
    public Integer getAsiHorasSemanales() {
        return this.asiHorasSemanales;
    }
    
    public void setAsiHorasSemanales(Integer asiHorasSemanales) {
        this.asiHorasSemanales = asiHorasSemanales;
    }
    public Boolean getAsiOptativa() {
        return this.asiOptativa;
    }
    
    public void setAsiOptativa(Boolean asiOptativa) {
        this.asiOptativa = asiOptativa;
    }




}


