package com.dicampus.j2ee.model;
// Generated 24 ago 2026, 14:07:38 by Hibernate Tools 5.4.33.Final



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private static final long serialVersionUID = 8809695370157814377L;
	 private Long curId;
     private long curEnsId;
     private String curNombre;

    public Curso() {
    }

	
    public Curso(long curEnsId) {
        this.curEnsId = curEnsId;
    }
    public Curso(long curEnsId, String curNombre) {
       this.curEnsId = curEnsId;
       this.curNombre = curNombre;
    }
   
    public Long getCurId() {
        return this.curId;
    }
    
    public void setCurId(Long curId) {
        this.curId = curId;
    }
    public long getCurEnsId() {
        return this.curEnsId;
    }
    
    public void setCurEnsId(long curEnsId) {
        this.curEnsId = curEnsId;
    }
    public String getCurNombre() {
        return this.curNombre;
    }
    
    public void setCurNombre(String curNombre) {
        this.curNombre = curNombre;
    }




}


