package com.dicampus.j2ee.model;
// Generated 24 ago 2026, 14:07:38 by Hibernate Tools 5.4.33.Final



/**
 * Ensenanza generated by hbm2java
 */
public class Ensenanza  implements java.io.Serializable {


     private static final long serialVersionUID = 1271287055714836151L;
	 private Long ensId;
     private String ensNombre;
     private Integer ensDuracion;
     private Integer ensEdadMinima;
     private Integer ensEdadMaxima;

    public Ensenanza() {
    }

    public Ensenanza(String ensNombre, Integer ensDuracion, Integer ensEdadMinima, Integer ensEdadMaxima) {
       this.ensNombre = ensNombre;
       this.ensDuracion = ensDuracion;
       this.ensEdadMinima = ensEdadMinima;
       this.ensEdadMaxima = ensEdadMaxima;
    }
   
    public Long getEnsId() {
        return this.ensId;
    }
    
    public void setEnsId(Long ensId) {
        this.ensId = ensId;
    }
    public String getEnsNombre() {
        return this.ensNombre;
    }
    
    public void setEnsNombre(String ensNombre) {
        this.ensNombre = ensNombre;
    }
    public Integer getEnsDuracion() {
        return this.ensDuracion;
    }
    
    public void setEnsDuracion(Integer ensDuracion) {
        this.ensDuracion = ensDuracion;
    }
    public Integer getEnsEdadMinima() {
        return this.ensEdadMinima;
    }
    
    public void setEnsEdadMinima(Integer ensEdadMinima) {
        this.ensEdadMinima = ensEdadMinima;
    }
    public Integer getEnsEdadMaxima() {
        return this.ensEdadMaxima;
    }
    
    public void setEnsEdadMaxima(Integer ensEdadMaxima) {
        this.ensEdadMaxima = ensEdadMaxima;
    }




}


